    var bankName = `[{
      "bankCode": "701",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Kho bạc nhà nước tỉnh thành phố",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "KBNN-KHO BAC NHA NUOC TINH, TP",
      "nameGB": "KBNN-KHO BAC NHA NUOC TINH, TP"
    },
    {
      "bankCode": "659",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Ấn Độ (Bank of India)",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BANK OF INDIA-NH BANK OF INDIA",
      "nameGB": "BANK OF INDIA-NH BANK OF INDIA"
    },
    {
      "bankCode": "612",
      "mnemonic": "BANGKOKBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng BangKok Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BANGKOK-NH BANGKOK TAI VN",
      "nameGB": "BANGKOK-NH BANGKOK TAI VN"
    },
    {
      "bankCode": "657",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng BNP Paribas Hà Nội",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BNP PARIBAS-NH BNP PARIBAS CN HANOI",
      "nameGB": "BNP PARIBAS-NH BNP PARIBAS CN HANOI"
    },
    {
      "bankCode": "614",
      "mnemonic": "BNPPARIBAS",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng BNP Paribas Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BNP PARIBAS-NH BNP PARIBAS CN HCM",
      "nameGB": "BNP PARIBAS-NH BNP PARIBAS CN HCM"
    },
    {
      "bankCode": "601",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng BPCEIOM",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BPCEIOM-NGAN HANG BPCEIOM",
      "nameGB": "BPCEIOM-NGAN HANG BPCEIOM"
    },
    {
      "bankCode": "660",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Busan",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BUSAN-NGAN HANG BUSAN",
      "nameGB": "BUSAN-NGAN HANG BUSAN"
    },
    {
      "bankCode": "634",
      "mnemonic": "NHCATHAY",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "510",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Cathay",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CATHAY-NH CATHAY",
      "nameGB": "NH CATHAY"
    },
    {
      "bankCode": "611",
      "mnemonic": "CHINACONSTRUCTIONBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng China Construction",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CCB-NH CHINA CONSTRUCTION",
      "nameGB": "CCB-NH CHINA CONSTRUCTION"
    },
    {
      "bankCode": "620",
      "mnemonic": "BANKOFCHINA",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng China tại Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CHINA BANK-NH CHINA TAI VN",
      "nameGB": "CHINA BANK-NH CHINA TAI VN"
    },
    {
      "bankCode": "605",
      "mnemonic": "CITIBANKHANOI",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Citi Hà Nội",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CITIBANK-NH CITI BANK HA NOI",
      "nameGB": "CITIBANK-NH CITI BANK HA NOI"
    },
    {
      "bankCode": "654",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Citibank Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CITIBANK-NH CITIBANK CN TP HCM-HO",
      "nameGB": "CITIBANK-NH CITIBANK CN TP HCM-HO"
    },
    {
      "bankCode": "643",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Commonweal",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "COMMBANK-NH COMMONWEALTH VN",
      "nameGB": "COMMONWEALTH BANK"
    },
    {
      "bankCode": "615",
      "mnemonic": "BANKOFCOMMUNICATIONS",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Communications Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BOCOMM-NH COMMUNICATIONS TAI VN",
      "nameGB": "BOCOMM-NH COMMUNICATIONS TAI VN"
    },
    {
      "bankCode": "649",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Công thương Trung Quốc (ICBC)",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "ICBC-NH INDUSTRIAL AND COM OF CHINA",
      "nameGB": "ICBC-NH INDUSTRIAL AND COM OF CHINA"
    },
    {
      "bankCode": "621",
      "mnemonic": "CREDITAGRICODECIBBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Credit Agricode CIB Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "CACIB-NH CREDIT AGRICODE CIB",
      "nameGB": "CACIB-NH CREDIT AGRICODE CIB"
    },
    {
      "bankCode": "207",
      "mnemonic": "VBSP",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng chính sách xã hội ",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "VBSP-NH CHINH SACH XA HOI",
      "nameGB": "VBSP-NH CHINH SACH XA HOI"
    },
    {
      "bankCode": "652",
      "mnemonic": "IBK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng công nghiệp Hàn Quốc",
      "joinNapas": true,
      "bankID": "970455",
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "IBK-NH CONG NGHIEP HAN QUOC",
      "nameGB": "IBK-NH CONG NGHIEP HAN QUOC"
    },
    {
      "bankCode": "619",
      "mnemonic": "DEUTSCHEBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Deutsche Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "DP-NH DEUTSCHE BANK TAI VN",
      "nameGB": "DP-NH DEUTSCHE BANK TAI VN"
    },
    {
      "bankCode": "638",
      "mnemonic": "BIDCCNHN",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Đầu tư và Phát triển Campuchia Hà Nội",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BIDC-NH DT VA PT CAMPUCHIA CN HN",
      "nameGB": "BIDC-NH DT VA PT CAMPUCHIA CN HN"
    },
    {
      "bankCode": "648",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Đầu tư và Phát triển Campuchia Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BIDC-NH DT VA PT CAMPUCHIA CN TPHCM",
      "nameGB": "BIDC-NH DT VA PT CAMPUCHIA CN TPHCM"
    },
    {
      "bankCode": "202",
      "mnemonic": "BIDV",
      "customerID": "100153",
      "address": "HANG VOI",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "19",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Đầu tư và Phát triển VN (BIDV)",
      "joinNapas": true,
      "bankID": "970418",
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "BIDV-NH TMCP DT VA PHAT TRIEN VN",
      "nameGB": "BIDV-NH TMCP DT VA PHAT TRIEN VN"
    },
    {
      "bankCode": "608",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng First Commercial Hà Nội",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "FCB-NH FIRST COMMERCIAL CN HA NOI",
      "nameGB": "FCB-NH FIRST COMMERCIAL CN HA NOI"
    },
    {
      "bankCode": "630",
      "mnemonic": "FISTCOMMERCIALBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng First Commercial Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "FCB-NH FIRST COMMERCIAL CN HCM",
      "nameGB": "FCB-NH FIRST COMMERCIAL CN HCM"
    },
    {
      "bankCode": "656",
      "mnemonic": "",
      "customerID": "",
      "address": "TP HCM",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Hana Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "HANABANK-NH HANA CN TPHCM",
      "nameGB": "HANABANK-NH HANA CN TPHCM"
    },
    {
      "bankCode": "640",
      "mnemonic": "HUANANCOMMERCIALBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Huanan Commercial Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "HNCB-NH HUA NAN COMMERCIAL TAI VN",
      "nameGB": "HNCB-NH HUA NAN COMMERCIAL TAI VN"
    },
    {
      "bankCode": "901",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng hợp tác xã Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "COOPBANK-NH HOP TAC XA VN",
      "nameGB": "COOPBANK-NH HOP TAC XA VN"
    },
    {
      "bankCode": "641",
      "mnemonic": "",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Industrial Korea",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "IBK-NH INDUSTRIAL BANK OF KOREA",
      "nameGB": "IBK-NH INDUSTRIAL BANK OF KOREA"
    },
    {
      "bankCode": "627",
      "mnemonic": "JPMORGANCHASEN.A",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Jpmorgan Chase N.A",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "JPM-NH JPMORGAN CHASE N.A",
      "nameGB": "JPM-NH JPMORGAN CHASE N.A"
    },
    {
      "bankCode": "631",
      "mnemonic": "KOOKMINBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Koodmin Hồ Chí Minh",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "KOOKMIN-NH KOOKMIN CN TPHCM",
      "nameGB": "KOOKMIN-NH KOOKMIN CN TPHCM"
    },
    {
      "bankCode": "626",
      "mnemonic": "KOREAEXCHANGEBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Korea Exchange Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "KEB-NH KOREA EXCHANGE BANK",
      "nameGB": "KEB-NH KOREA EXCHANGE BANK"
    },
    {
      "bankCode": "635",
      "mnemonic": "MALAYANBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Malayan Herhad",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "MAYBANK-NH MALAYAN BANKING BERHAD",
      "nameGB": "MAYBANK-NH MALAYAN BANKING BERHAD"
    },
    {
      "bankCode": "609",
      "mnemonic": "MAYBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng MayBank Hà Nội",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "MAYBANK-NH MAYBANK HA NOI",
      "nameGB": "MAYBANK-NH MAYBANK HA NOI"
    },
    {
      "bankCode": "623",
      "mnemonic": "MEGAICBCBANK",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "8",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Mega ICBC Việt Nam",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "MEGA-NH MEGA ICBC BANK",
      "nameGB": "MEGA-NH MEGA ICBC BANK"
    },
    {
      "bankCode": "639",
      "mnemonic": "MIZUHO",
      "customerID": "",
      "address": "",
      "countryID": "VN",
      "cityID": "4",
      "districtID": "",
      "organizationType": "NH",
      "nostroAccount": "",
      "nostroCcy": "",
      "bankName": "Ngân hàng Mizuho Corporate",
      "joinNapas": false,
      "bankID": null,
      "logoBaseSF": null,
      "logoByte": null,
      "nameVI": "MIZUHO-NH MIZUHO CORPORATE BANK",
      "nameGB": "MIZUHO-NH MIZUHO CORPORATE BANK"
    }]`;